
const mongoose = require("mongoose");

const aiDiagnosticSchema = new mongoose.Schema(
  {
    testId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TestReport",
      required: true,
    },
    summary: String, // e.g., "AI detected 3 anomalies"
    insights: [String], // e.g., ["Anomaly in hemoglobin", "High white cell count"]
    accuracy: Number, // e.g., 98.7
    processingTimeReduction: Number, // e.g., -67
    anomalies: [String], // list of flagged results
    patterns: [String], // e.g., ["Pattern matches respiratory distress"]
    autoGeneratedReport: String, // text of the generated report
    createdByAI: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);


module.exports = mongoose.model("AIDiagnostic", aiDiagnosticSchema);
